/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradleframework;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should be greater than zero", classUnderTest.someLibraryMethod() > 0);
    }
}
