/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package testapp;

import gradleframework.Library;

public class App {
    public String getGreeting() {

        var d = new Library();

        var result = d.someLibraryMethod();

        return "Hello World!" + result;
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
